spring.application.name=tarefas
spring.datasource.url=jdbc:postgresql://localhost:5433/tarefas
spring.datasource.username=postgres
spring.datasource.password=caroline
spring.datasource.driver-class-name=org.postgresql.Driver